export const PROJECTS = [
  {
    title: "Sokoni Fresh",
    cat: "E-commerce platform",
    year: "2025",
    time: "9 weeks",
    seed: "finaki-soko5",
    service: "web",
    desc: "A farm-to-door grocery platform for Nairobi — storefront, M-Pesa checkout and a delivery ops dashboard. Built in nine weeks; now moving four figures of orders a week.",
    del: ["UX & UI design", "Storefront build", "M-Pesa checkout", "Ops dashboard"],
  },
  {
    title: "Pesa Flow",
    cat: "Software & data",
    year: "2025",
    time: "8 weeks",
    seed: "finaki-pesa5",
    service: "software",
    desc: "A payments-ops dashboard for a Nairobi fintech — reconciling M-Pesa, bank and card flows in one live view. A week of ops work, down to an hour.",
    del: ["Product UX", "Dashboard build", "M-Pesa & bank integrations", "Role-based access"],
  },
  {
    title: "Boda Shield",
    cat: "Site + quote agent",
    year: "2024",
    time: "6 weeks",
    seed: "finaki-boda5",
    service: "agents",
    desc: "Insurance for boda riders, explained like a human. Brand site plus an agent that quotes riders in under a minute — English or Kiswahili.",
    del: ["Brand & site", "Quote agent (EN/SW)", "Lead routing", "Analytics setup"],
  },
  {
    title: "Zawadi & Co.",
    cat: "Market entry — gifting",
    year: "2024",
    time: "One quarter",
    seed: "finaki-zawa5",
    service: "market",
    desc: "A Gulf-based gifting brand entering Kenya. Research, pricing, retail partnerships and the launch campaign that introduced them to Nairobi.",
    del: ["Market research", "Positioning & pricing", "Launch campaign", "Retail partnerships"],
  },
];

export const SERVICES = [
  {
    id: "web",
    num: "(01)",
    label: "Web & Product",
    title: "Web <em>&</em> Product",
    desc: "Sites, stores and products — designed to be remembered, built to convert.",
    chips: ["Marketing sites", "E-commerce", "Web apps", "Landing sprints"],
    seed: "finaki-web9",
    alt: "Web & product work",
    style: { "--i": 0, "--sp-bg": "#F4EFE4", "--sp-fg": "#12100C", "--sp-dim": "rgba(18,16,12,.6)", "--sp-line": "rgba(18,16,12,.16)" } as React.CSSProperties,
  },
  {
    id: "software",
    num: "(02)",
    label: "Software & Platforms",
    title: "Software <em>platforms</em>",
    desc: "Dashboards, internal tools and integrations shaped around how your team works.",
    chips: ["Internal tools", "Dashboards", "APIs & integrations", "MVP builds"],
    seed: "finaki-soft9",
    alt: "Software platforms work",
    style: { "--i": 1, "--sp-bg": "#1A130D", "--sp-fg": "#F4EFE4", "--sp-dim": "rgba(244,239,228,.6)", "--sp-line": "rgba(244,239,228,.15)" } as React.CSSProperties,
  },
  {
    id: "agents",
    num: "(03)",
    label: "AI Agents & Automation",
    title: "Agents <em>& bots</em>",
    desc: "Agents that reply, qualify and book while you sleep — in English or Kiswahili.",
    chips: ["Support agents", "Lead qualification", "WhatsApp bots", "Workflow automation"],
    seed: "finaki-agent9",
    alt: "AI agents work",
    style: { "--i": 2, "--sp-bg": "#F4EFE4", "--sp-fg": "#12100C", "--sp-dim": "rgba(18,16,12,.6)", "--sp-line": "rgba(18,16,12,.16)" } as React.CSSProperties,
  },
  {
    id: "market",
    num: "(04)",
    label: "Market Entry",
    title: "Market <em>entry</em>",
    desc: "Research, positioning, launch and distribution — we know the Kenyan terrain.",
    chips: ["Market research", "Go-to-market", "Partnerships", "Launch campaigns"],
    seed: "finaki-market9",
    alt: "Market entry work",
    style: { "--i": 3, "--sp-bg": "#FF4D00", "--sp-fg": "#160B05", "--sp-dim": "rgba(22,11,5,.66)", "--sp-line": "rgba(22,11,5,.25)", "--sp-em": "#160B05" } as React.CSSProperties,
  },
  {
    id: "brand",
    num: "(05)",
    label: "Brand & Growth",
    title: "Brand <em>&</em> growth",
    desc: "Identity, content and campaigns that keep the pipeline warm.",
    chips: ["Identity systems", "Content", "SEO", "Paid & organic"],
    seed: "finaki-brand9",
    alt: "Brand and growth work",
    style: { "--i": 4, "--sp-bg": "#1A130D", "--sp-fg": "#F4EFE4", "--sp-dim": "rgba(244,239,228,.6)", "--sp-line": "rgba(244,239,228,.15)" } as React.CSSProperties,
  },
];

export const CHAT_KB = [
  { re: /^(hi|hey|hello|yo|sasa|niaje|habari|mambo)\b/i, reply: "Niaje! I'm Fini — a demo agent built here at Finaki. Ask about pricing, speed, or what we build." },
  { re: /swahili|kiswahili/i, reply: "Ndio kabisa! Our agents speak Kiswahili and English — whichever your customers prefer." },
  { re: /m-?pesa|payment|integrat|api\b|whatsapp/i, reply: "We wire agents and platforms into M-Pesa, WhatsApp, CRMs and custom APIs." },
  { re: /agent|ai\b|bot|automat|chat/i, reply: "Agents that reply, qualify, book and follow up while you sleep — trained on your data. I'm a small demo of the idea." },
  { re: /market|kenya|entry|distribut/i, reply: "Research, positioning and pricing for the Kenyan market, then launch and distribution. We know the terrain." },
  { re: /fast|long|time|timeline|deadline|when|week|month/i, reply: "A site: 2–3 weeks. A platform: 6–10. An agent: days. Scoped in weeks, not quarters." },
  { re: /where|located|based|office|contact|email|phone|reach/i, reply: "Nairobi, Kenya — shipping worldwide. hello@finaki.studio, or the form below." },
  { re: /team|people|who are|how many/i, reply: "A small senior team — strategy, design and engineering under one roof." },
  { re: /price|cost|charge|how much|pricing|budget|expensive/i, reply: "Fixed scope, fixed price — agreed before we start. Sites from ~KES 120k; software and agents quoted to the problem." },
  { re: /build|make|service|website|web|software|app|platform|brand|design|what do/i, reply: "Websites, e-commerce, software, dashboards, AI agents, brand & growth — and market entry into Kenya." },
  { re: /start|begin|hire|project|quote|talk|meeting/i, cta: true, reply: "Easy. There's a form at the bottom of this page — name, email, the problem. We reply within one working day." },
];

export const CHAT_FALLBACK = "That's above my pay grade — I'm a small demo. Try pricing, timelines, or what we build.";

export const MARQUEE_A = ["E-commerce", "Brand", "Automation", "Growth"];
export const MARQUEE_B = ["Websites", "Software", "AI agents", "Market entry"];
